project:
  type: website
  output-dir: docs

website:
  title: "Jack Jewson"
  navbar:
    left:
      - href: index.qmd
        text: Home
  page-footer:
    center: "Jack Jewson · Monash University"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: article
